import { Request, Response, NextFunction } from "express"

import { ulid } from "ulid"

export function generateKey() {
  return ulid()
}

const storedKey = generateKey()

console.log(`AUTOGENERATED API_KEY: ${storedKey}`)

export async function checkApiKeys(
  req: Request,
  res: Response,
  next: NextFunction
) {
  const API_KEY = req.header("API_KEY")

  if (API_KEY !== storedKey) {
    res.status(401).json({
      error: "API_KEY",
      message: "API_KEY is missing or wrong, please try again."
    })
    return
  }

  next()
}
